# Generated by Django 6.0 on 2025-12-03 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.TextField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('telefone_responsavel', models.CharField(max_length=20)),
                ('email_responsavel', models.EmailField(max_length=254)),
                ('observacoes_medicas', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField()),
                ('tipo_consulta', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=100)),
                ('diagnostico', models.TextField()),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='monitoramento.idoso')),
            ],
            options={
                'ordering': ['-data_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('relogio', 'Relógio Inteligente'), ('pulseira', 'Pulseira Fitness'), ('sensor', 'Sensor Corporal'), ('outro', 'Outro')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=50, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True)),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='monitoramento.idoso')),
            ],
        ),
        migrations.CreateModel(
            name='DadoSaude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('pressao_sistolica', models.IntegerField(blank=True, null=True)),
                ('pressao_diastolica', models.IntegerField(blank=True, null=True)),
                ('saturacao_oxigenio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('passos', models.IntegerField(blank=True, null=True)),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('queda_detectada', models.BooleanField(default=False)),
                ('botao_emergencia', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bateria_dispositivo', models.IntegerField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados', to='monitoramento.dispositivo')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dados_saude', to='monitoramento.idoso')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('frequencia_cardiaca', 'Frequência Cardíaca'), ('pressao_arterial', 'Pressão Arterial'), ('queda', 'Queda Detectada'), ('emergencia', 'Botão de Emergência'), ('inatividade', 'Inatividade Prolongada'), ('bateria_baixa', 'Bateria Baixa'), ('desconexao', 'Desconexão do Dispositivo')], max_length=30)),
                ('nivel', models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto'), ('critico', 'Crítico')], max_length=10)),
                ('mensagem', models.TextField()),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('notificacao_email', models.BooleanField(default=False)),
                ('notificacao_sms', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('dado_saude', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoramento.dadosaude')),
                ('idoso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitoramento.idoso')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
